#!/bin/bash

# THIS SCRIPT IS USED TO GET THE HIGHEST FILES CONSUMING MEMORY


# TSORING THE LOG FILE
LOGSDIR=/tmp
DATE=$(date +%Y-%m-%d)
SCRIPT_NAME=$0
LOGFILE=$LOGSDIR/$SCRIPT_NAME-$DATE.log

# CHECKING WHETHERE ON ROOT USER OR NOT
USERID=$(id -u) &>>$LOGFILE
if [ $USERID -EN 0 ]
then
    echo "ERROR: PLEASE SWITCH TO ROOT USER"
    exit 1
fi 

# COMMAND TO GET THE TOP 5 FILES CONSUMING MORE MEMORY
FILEPATH=A$1 &>>$LOGFILE
FILE_SYSTEM_SIZE=$( sudo du -ah /etc | sort -hr | head -n 5) &>>$LOGFILE

